server:
  port: 8181
  error:
    whitelabel:
      enabled: true

debug: false

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

logging:
  level:
    root: info
  org:
    hibernate:
      SQL: debug
      type:
        descriptor:
          sql: trace

spring:
  devtools:
    livereload:
      enabled: true
#   timezone: Asia/Seoul
  datasource:
    url: jdbc:mysql://localhost:3306/design?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: design
    password: dlatl!00
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    # MySQL8Dialect has been deprecated; use org.hibernate.dialect.MySQLDialect instead
    # database-platform: org.hibernate.dialect.MySQLDialect
    # database: h2
    # datasource:
    #   url: jdbc:mysql://localhost:3306/getinline?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #   driver-class-name: com.mysql.cj.jdbc.Driver
    #   username: design
    #   password: dlatl!00
    hibernate:
    #   ddl-auto: create
    #   ddl-auto: validate
      hbm2ddl:
        auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  h2:
    console:
      # devtools 의 환경에서는 true 이므로, 명시적으로 false 로 설정함
      enabled: false
  # timezone: UTC

    basename: messages
    encoding: UTF-8
    # basename은 messages.properties 파일의 경로입니다.
    # encoding은 메시지 파일의 인코딩입니다.
    # default-locale은 메시지의 기본 언어입니다.
    # Springboot 애플리케이션의 모든 출력 메시지가 한글로 출력
    default-locale: ko_KR
  # must not be empty의 한글 메시지입니다.
  messages.must-not-be-empty: 필수 입력입니다.
  # 콘솔에 색상을 넣음
  output:
    ansi:
      enabled: always






