server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql//localhost:3306/design?serverTime=Asia/Seoul&characterEncoding=UTF-8
    username: design
    password: dlatl!00

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # database: h2
    datasource:
      url: jdbc:mysql//localhost:3306/design?serverTime=Asia/Seoul&characterEncoding=UTF-8
      username: design
      password: dlatl!00
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      # devtools 의 환경에서는 true 이므로, 명시적으로 false 로 설정함
      enabled: true
  # timezone: UTC
  timezone: Asia/Seoul
  messages:
    basename: messages
    encoding: UTF-8
    # basename은 messages.properties 파일의 경로입니다.
    # encoding은 메시지 파일의 인코딩입니다.
    # default-locale은 메시지의 기본 언어입니다.
    # Springboot 애플리케이션의 모든 출력 메시지가 한글로 출력
    default-locale: ko_KR
  # must not be empty의 한글 메시지입니다.
  messages.must-not-be-empty: 필수 입력입니다.
  # 콘솔에 색상을 넣음
  output:
    ansi:
      enabled: always





management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

logging:
  level:
    root: info
