server:
  port: 8181
  error:
    whitelabel:
      enabled: true

debug: false

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

logging:
  level:
    root: info # root level(전체) 로깅 레벨 지정
    org:
        hibernate:
        SQL: debug
        type:
            descriptor:
              sql: trace  # ? 에 어떤 값이 들어갔는지 확인하기

spring:
  devtools:
    livereload:
      enabled: true
  
  datasource:
    url: jdbc:mysql://localhost:3306/design?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: design
    password: dlatl!00
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    # MySQL8Dialect has been deprecated; use org.hibernate.dialect.MySQLDialect instead
    # database-platform: org.hibernate.dialect.MySQLDialect
    # database: h2
    # datasource:
    #   url: jdbc:mysql://localhost:3306/getinline?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #   driver-class-name: com.mysql.cj.jdbc.Driver
    #   username: design
    #   password: dlatl!00
    hibernate:
      ddl-auto: create        # 생성(스키마 생성)
      # ddl-auto: update      # 업데이트(변경된 경우 스키마 업데이트)
      # ddl-auto: validate    # 유효성 검사 (스키마 유효성 검사)
      # ddl-auto: none        # 아무것도 하지 않음
      # ddl-auto: create-drop # 스키마를 생성하고 마지막에 드롭
    show-sql: true            # query 를 보여줌
    open-in-view: false
    properties:
      hibernate:
        format_sql: true               # 예쁘게 보기
        use_sql_comments: true         # 추가적인 주석 표시
        default_batch_fetch_size: 100  # 배치 처리
  h2:
    console:
      # devtools 의 환경에서는 true 이므로, 명시적으로 false 로 설정함
      enabled: false


  # ansi 터미널을 지원한다면 console에 색상 추가 가능
  output:
    ansi:
      enabled: always






